version: "3.8"
services:
  my-node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:ro
      - /egg/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: always